# Generated by Django 3.2.18 on 2023-05-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230518_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='answerCnt',
            field=models.IntegerField(default=0),
        ),
    ]
